name: Build Amiral Titan APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04  # On force une version plus stable pour le build Android
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git python3-dev ffmpeg libsdl2-dev libsdl2-image-dev \
            libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev \
            libavformat-dev libavcodec-dev zlib1g-dev libgstreamer1.0-dev \
            gstreamer1.0-plugins-base gstreamer1.0-plugins-good libffi-dev \
            libssl-dev openjdk-17-jdk zip unzip autoconf libtool pkg-config \
            cmake gettext
          pip install --upgrade pip
          pip install buildozer cython==0.29.33 kivy pandas requests

      - name: Build with Buildozer
        run: |
          buildozer android debug
        env:
          ACCEPT_SDK_LICENSE: "yes"
          BUILDOZER_LOG_LEVEL: "2"
          BUILDOZER_ALLOW_ORG_NAME_AS_DOMAIN: "1"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Amiral-Titan-APK
          path: bin/*.apk
